version: '2'
services:
    db:
        image: ae/vpn-db
        ports:
         - "15432:5432"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ttBsXoOvcqdoweDc
    backend:
        image: ae/vpn-backend
        volumes:
            - ../logs:/root/logs
        network_mode: "host"
        command: sh -c "sleep 5; touch backend.jar; java -jar -Djava.security.egd=file:/dev/./urandom backend.jar"